name: Build

on:
  push:
    branches:
      - main

env:
  RUBY_VERSION: 3.2.2

jobs:
  client-data:
    name: Client Data
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/unlightcloud/castle
      options: --user root
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: unlight
          MYSQL_PASSWORD: unlight
          MYSQL_DATABASE: unlight_db
          MYSQL_ROOT_PASSWORD: unlight
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
      memcached:
        image: memcached:alpine
        ports:
          - 11211:11211
    steps:
      - run: cd /opt/unlight && bundle exec rake db:migrate
        env:
          MEMCACHED_HOST: "memcached:11211"
          DATABASE_URL: "mysql2://unlight:unlight@mysql:3306/unlight_db?encoding=utf8"
      - run: cd /opt/unlight && bundle exec rake data:import
        env:
          MEMCACHED_HOST: "memcached:11211"
          DATABASE_URL: "mysql2://unlight:unlight@mysql:3306/unlight_db?encoding=utf8"
      - run: cd /opt/unlight && bundle exec rake data:generate_client_data
        env:
          MEMCACHED_HOST: "memcached:11211"
          DATABASE_URL: "mysql2://unlight:unlight@mysql:3306/unlight_db?encoding=utf8"
      - run: mkdir -p data/export
      - run: cp -r /opt/unlight/tmp/export/* data/export
      - name: Upload Client Data
        uses: actions/upload-artifact@v4
        with:
          name: client-data
          path: data/export
  generate:
    name: Generate
    runs-on: ubuntu-latest
    needs: client-data
    steps:
      - name: Download Client Data
        uses: actions/download-artifact@v4
        with:
          name: client-data
          path: data/export
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Constant Data
        run: ruby scripts/create_const_data.rb
      - name: Font Loader
        run: ruby scripts/create_font_loader.rb
      - name: Refresh Version
        run: ruby scripts/refresh_version.rb
      - name: Upload Constant Data
        uses: actions/upload-artifact@v4
        with:
          name: constant-data
          path: src/model/utils/ConstData.as
      - name: Upload Font Loader
        uses: actions/upload-artifact@v4
        with:
          name: font-loader
          path: src/FontLoader.as
      - name: Upload Version
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: lib/Version.as
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: generate
    container:
      image: ghcr.io/unlightcloud/flex-sdk
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Download Constant Data
        uses: actions/download-artifact@v4
        with:
          name: constant-data
          path: src/model/utils/
      - name: Download Font Loader
        uses: actions/download-artifact@v4
        with:
          name: font-loader
          path: src/
      - name: Download Version
        uses: actions/download-artifact@v4
        with:
          name: version
          path: lib/
      - name: Build
        run: mxmlc ./src/Unlight.mxml
      - name: Upload SWF
        uses: actions/upload-artifact@v4
        with:
          name: Unlight
          path: src/Unlight.swf
